### ISSUE TITLE
Version 2.0.4 has bad behavior with version 27 of jest-environment-jsdom

### ISSUE THREAD

**Issue by kaiyoma** [simon360/jest-environment-jsdom-global#47]
This week, I upgraded jest-environment-jsdom from 26.6.2 to 27.0.3 and I'm now seeing some issues that I believe are related to this package. If I run multiple test files at once, everything is fine, but if I run a single test file, then there's a crash in this package:

```
  ● Test suite failed to run

    evalmachine.<anonymous>:1
    AggregateError
    ^

    ReferenceError: AggregateError is not defined

      at evalmachine.<anonymous>:1:1
      at setupWindow (node_modules/jsdom/lib/jsdom/browser/Window.js:111:55)
      at new Window (node_modules/jsdom/lib/jsdom/browser/Window.js:223:3)
      at exports.createWindow (node_modules/jsdom/lib/jsdom/browser/Window.js:95:10)
      at new JSDOM (node_modules/jsdom/lib/api.js:36:20)
      at new JSDOMEnvironmentGlobal (node_modules/jest-environment-jsdom-global/environment.js:12:5)
```

I think issue #46 is related.

**Comment by kaiyoma** [comment]
I ended up debugging this with some of the jsdom folks and we narrowed down the problem to polyfills. I added an explanation here: https://github.com/jsdom/jsdom/issues/3205#issuecomment-861902957
