### ISSUE TITLE
Error: Not implemented: navigation (except hash changes)

### ISSUE THREAD

**Issue by JPStrydom** [simon360/jest-environment-jsdom-global#9]
I receive the following error when running my tests:

```
Error: Not implemented: navigation (except hash changes)
at module.exports (...\node_modules\jsdom\lib\jsdom\browser\not-implemented.js:9:17)
at navigateFetch (...\node_modules\jsdom\lib\jsdom\living\window\navigation.js:74:3)
at exports.navigate (...\node_modules\jsdom\lib\jsdom\living\window\navigation.js:52:3)
at LocationImpl._locationObjectNavigate (...\node_modules\jsdom\lib\jsdom\living\window\Location-impl.js:29:5)
at LocationImpl._locationObjectSetterNavigate (...\node_modules\jsdom\lib\jsdom\living\window\Location-impl.js:23:17)
at LocationImpl.set pathname [as pathname] (...\node_modules\jsdom\lib\jsdom\living\window\Location-impl.js:151:10)
at Location.set [as pathname] (...\node_modules\jsdom\lib\jsdom\living\generated\Location.js:293:31)
at Object.it (...\src\services\sub-services\supported-browser-service\test\supported-browser-service.spec.js:52:38)
at Object.asyncJestTest (...\node_modules\jest-jasmine2\build\jasmine_async.js:108:37)
at resolve (...\node_modules\jest-jasmine2\build\queue_runner.js:56:12) undefined
```

I've tried the following two methods of dynamically updating my URL but I still receive the error:
```
global.jsdom.reconfigure({
    url: `https://www.${hostname}`
});
```
and
```
jsdom.reconfigure({
    url: `https://www.${hostname}`
});
```

The tests still pass for some reason, just curious if this is something I should be concerned about?

NOTE:

Here are my dependencies in `package.json`:
```
{
...
    ,
    "dependencies": {
        "axios": "0.18.0",
        "bowser": "2.0.0-beta.3",
        "classnames": "2.2.6",
        "dashjs": "2.9.2",
        "get-countries-info": "1.2.1",
        "lodash": "4.17.11",
        "moment": "2.22.2",
        "nuka-carousel": "4.3.5",
        "prop-types": "15.6.2",
        "querystringify": "2.0.0",
        "rc-slider": "8.6.3",
        "react": "16.5.2",
        "react-custom-scrollbars": "4.2.1",
        "react-dom": "16.5.2",
        "react-icons-kit": "1.1.7",
        "react-image-fallback": "8.0.0",
        "react-lottie": "1.2.3",
        "react-markdown": "3.6.0",
        "react-player-controls": "0.5.21",
        "react-redux": "5.0.7",
        "react-router-dom": "4.3.1",
        "react-select": "2.0.0",
        "react-toastify": "3.4.3",
        "redux": "4.0.1",
        "redux-promise": "0.6.0",
        "redux-thunk": "2.3.0",
        "validator": "10.7.1"
    },
    "devDependencies": {
        "autoprefixer": "9.1.5",
        "babel-core": "6.26.3",
        "babel-eslint": "9.0.0",
        "babel-jest": "23.6.0",
        "babel-loader": "7.1.2",
        "babel-preset-react-app": "3.1.2",
        "babel-runtime": "6.26.0",
        "case-sensitive-paths-webpack-plugin": "2.1.2",
        "chalk": "2.4.1",
        "css-loader": "1.0.0",
        "dotenv": "6.0.0",
        "dotenv-expand": "4.2.0",
        "enzyme": "3.7.0",
        "enzyme-adapter-react-16": "1.6.0",
        "enzyme-matchers": "6.0.4",
        "eslint": "4.19.1",
        "eslint-config-prettier": "3.0.1",
        "eslint-config-react-app": "2.1.0",
        "eslint-loader": "2.1.1",
        "eslint-plugin-flowtype": "2.50.0",
        "eslint-plugin-import": "2.14.0",
        "eslint-plugin-jest": "21.25.1",
        "eslint-plugin-jsx-a11y": "6.1.1",
        "eslint-plugin-prettier": "3.0.0",
        "eslint-plugin-react": "7.11.1",
        "extract-text-webpack-plugin": "3.0.2",
        "file-loader": "2.0.0",
        "fs-extra": "7.0.0",
        "generate-react-code": "1.3.0",
        "html-webpack-plugin": "3.2.0",
        "husky": "0.14.3",
        "jest": "23.6.0",
        "jest-environment-jsdom": "23.4.0",
        "jest-environment-jsdom-global": "1.1.0",
        "jest-enzyme": "7.0.0",
        "jest-localstorage-mock": "2.2.0",
        "jest-mock-console": "0.4.0",
        "lint-staged": "7.3.0",
        "moxios": "0.4.0",
        "node-sass-chokidar": "1.3.3",
        "npm-run-all": "4.1.3",
        "object-assign": "4.1.1",
        "postcss-flexbugs-fixes": "4.1.0",
        "postcss-loader": "3.0.0",
        "prettier": "1.14.3",
        "promise": "8.0.2",
        "raf": "3.4.0",
        "react-dev-utils": "5.0.2",
        "react-redux-mock": "0.2.2",
        "redux-devtools-extension": "2.13.5",
        "redux-logger": "3.0.6",
        "resolve": "1.8.1",
        "style-loader": "0.23.0",
        "sw-precache-webpack-plugin": "0.11.5",
        "url-loader": "1.1.1",
        "webpack": "3.12.0",
        "webpack-dev-server": "2.11.3",
        "webpack-manifest-plugin": "2.0.3",
        "whatwg-fetch": "2.0.4"
    },
    ....
}
```

Here is my `jest-setup.json` file:
```
{
    "collectCoverageFrom": ["**/*.js"],
    "setupFiles": ["<rootDir>/config/polyfills.js", "jest-localstorage-mock"],
    "setupTestFrameworkScriptFile": "<rootDir>/jest-setup/setup-tests.js",
    "testMatch": ["<rootDir>/src/**/?(*.)(spec|test).{js,jsx,mjs}"],
    "testEnvironment": "jest-environment-jsdom-global",
    "testURL": "http://localhost",
    "transform": {
        "^.+\\.(js|jsx|mjs)$": "<rootDir>/node_modules/babel-jest",
        "^.+\\.css$": "<rootDir>/config/jest/css-transform.js",
        "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/config/jest/file-transform.js"
    },
    "transformIgnorePatterns": ["[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"],
    "moduleFileExtensions": ["web.js", "js", "json", "web.jsx", "jsx", "node", "mjs"],
    "coverageThreshold": {
        "global": {
            "statements": 99,
            "branches": 99,
            "functions": 99,
            "lines": 99
        }
    }
}
```

**Comment by simon360** [comment]
@JPStrydom sorry for the late response here!

Hm, strange. I can't seem to reproduce that here - I've added a test [here](https://github.com/simon360/jest-environment-jsdom-global/blob/b94d48da660ab315d49e30324b1e8d01f11b0df7/__tests__/tests.js#L39), just in case, but to no avail.

That _looks_ like a proper exception being thrown, so it's surprising that your tests are still passing. I'm curious what else might be going on here. In particular, this part of the stack trace:

```
at Object.it (...\src\services\sub-services\supported-browser-service\test\supported-browser-service.spec.js:52:38)
```

Is the `reconfigure` at line 52 of that file?

Is there any chance you could provide a sample repo that reproduces this?

If you add an `expect(true).toBe(false)` _after_ the call to `.reconfigure`, do the tests fail (as they should)? Or do they bail out as soon as they hit the `reconfigure` call?

**Comment by simon360** [comment]
Closing this. If you still have trouble, feel free to reach out again.
